version: "3.8"
services:
  execution:
    image: ethereum/client-go:v1.14.13
    command:
      - --networkid=${CHAIN_ID}
      - --state.scheme=hash
      - --verbosity=3
      - --datadir=/execution-data
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.vhosts=*
      - --http.corsdomain=*
      - --http.api=engine,net,eth,web3,debug,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=engine,net,eth,web3,debug,txpool
      - --ws.origins=*
      - --nat=extip:${IP_ADDRESS}
      - --authrpc.port=8551
      - --authrpc.addr=0.0.0.0
      - --authrpc.vhosts=*
      - --authrpc.jwtsecret=/el-cl-genesis-data/jwt/jwtsecret
      - --syncmode=full
      - --gcmode=archive
      - --history.state=0
      - --history.transactions=0
      - --port=30303
      - --discovery.port=30303
      - --bootnodes=${EL_BOOTNODES}
    volumes:
      - ./execution-data:/execution-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "30303:30303/tcp"
      - "30303:30303/udp"
    restart: unless-stopped
    logging: 
      options:
        max-size: "100m" # Set maximum log file size
        max-file: "2" # Set maximum number of log files

  beacon:
    image: blocxtech/lighthouse:v1.0.1
    command:
      - lighthouse
      - beacon_node
      - --debug-level=info
      - --datadir=/consensus-data
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --enr-address=${IP_ADDRESS}
      - --enr-udp-port=9000
      - --enr-tcp-port=9000
      - --enr-quic-port=9001
      - --reconstruct-historic-states
      - --hierarchy-exponents=5,7,11
      - --genesis-backfill
      - --listen-address=0.0.0.0
      - --port=9000
      - --http
      - --http-address=0.0.0.0
      - --http-port=5052
      - --execution-endpoints=http://execution:8551
      - --jwt-secrets=/el-cl-genesis-data/jwt/jwtsecret
      - --subscribe-all-subnets
      - --import-all-attestations
      - --disable-peer-scoring
      - --trusted-peers=${CL_TRUSTPEERS}
      - --boot-nodes=${CL_BOOTNODES}
      - --checkpoint-sync-url=${CL_CHECKPOINT}
    volumes:
      - ./consensus-data:/consensus-data
      - ./el-cl-genesis-data:/el-cl-genesis-data
    ports:
      - "9002:9000/tcp"
      - "9003:9000/udp"
      - "9001:9001/udp"
      - "5052:5052"
      - "5054:5054"
    depends_on:
      - execution
    restart: unless-stopped
    logging: 
      options:
        max-size: "100m"
        max-file: "2" 

  validator:
    image: blocxtech/lighthouse:v1.0.1
    command:
      - lighthouse
      - validator_client
      - --debug-level=info
      - --testnet-dir=/el-cl-genesis-data/custom_config_data
      - --validators-dir=/validator_keys
      - --secrets-dir=/validator_keys_secrets
      - --init-slashing-protection
      - --beacon-nodes=http://beacon:5052
      - --suggested-fee-recipient=${FEE_RECIPIENT}
    volumes:
      - ./el-cl-genesis-data:/el-cl-genesis-data
      - ./keys/validator_keys:/validator_keys
      - ./keys/validator_keys_secrets:/validator_keys_secrets
    depends_on:
      - beacon
    restart: unless-stopped
    logging:
      options:
        max-size: "100m"
        max-file: "2"